language: perl
#group:    stable
#dist:     trusty
#os:       linux

sudo: false

perl:
  - '5.8'
  - '5.24'
  - '5.26'

env:
  - PERL_MM_USE_DEFAULT=1 TEST_AUTHOR=1

cache:
  directories:
    - perl_modules

before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - cpanm --notest local::lib
  - eval "$(perl -Mlocal::lib=${PWD}/perl_modules)"
  - build-dist
  - cd $BUILD_DIR

# travis seems to issue cpanm --quiet --installdeps --notest . for us somewhere
# after the last <before_install> and somewhere before the first <script>

script:
  - make test
